#!/bin/bash
# Specify jobname:
#SBATCH --job-name=si_bulk
# Specify the number of nodes and the number of CPU's (tasks) per node:
#SBATCH --nodes=1 --ntasks-per-node=4
# Specify account. 
#SBATCH --account=ln0003k
# The maximum time allowed for the job, in hh:mm:ss
#SBATCH --time=00:10:00
# Need more RAM? See http://www.uio.no/english/services/it/research/hpc/abel/help/user-guide/job-scripts.html#Large_Memory_Jobs
#SBATCH --mem-per-cpu=3800M
#SBATCH --exclusive


## Set up job environment    
module load vasp
source /cluster/bin/jobsetup
ulimit -l unlimited
ulimit -s unlimited
ulimit -m unlimited


## Run command 
mpirun ~olem/fm4111/bin/vasp.x
